anchors:
  lg:
  - 43.19310559006211
  - 50.995572519083964
  - 59.81746359223294
  md:
  - 19.55103626943005
  - 27.203208722741433
  - 35.17562231759656
  sm:
  - 2.650371318822021
  - 7.444496919917864
  - 12.86779279279279
audio_extension: wav
dropout: 0.3
melspectrogram_config:
  center: false
  hop_length: 1000
  mel_scale: htk
  n_fft: 1000
  n_mels: 32
  norm: slaney
  pad_mode: reflect
  power: 2
  win_length: null
mfcc_config:
  melkwargs:
    center: false
    hop_length: 1000
    mel_scale: htk
    n_fft: 1000
    n_mels: 32
    norm: slaney
    pad_mode: reflect
    power: 2
    win_length: null
  n_mfcc: 32
new_sample_rate: 16000
scale_input: true
num_anchors: 3
sample_duration: 120
sample_rate: 22050
taper_input: true
taper_window: hann
backbone: "custom"
block_layers: [3, 4, 6, 3]
resnet_config:
  block: "BasicBlock"
train_config:
  annotation_file_path: dataset/annotations/MD_mapping.json
  annotator: annotator_a
  batch_size: 32
  device: cuda
  epochs: 50
  ignore_index: -100
  label_smoothing: 0.0
  iou_confidence: true
  ignore_conf_threhold: 0.5
  loss_weights:
    class_loss_w: 5.0
    noobj_loss_w: 0.5
    obj_loss_w: 10.0
    segment_loss_w: 5.0
  optimizer_config:
    lr: 0.001
    weight_decay: 5.0e-04
    betas: [0.9, 0.999]
    eps: 0.00000001
    name: Adam
  lr_scheduler_config:
    T_0: 50
    T_mult: 1
    eta_min: 1.0e-05
    name: CosineAnnealingWarmRestarts
  metrics_path: metrics
  model_path: saved_model
  scale_segments: true
  shuffle_samples: true
  use_lr_scheduler: true
  verbose: true