anchors:
  lg:
  - 44.70780701754382
  - 52.36519855595674
  - 59.91998569384765
  md:
  - 21.138245614035124
  - 28.70468354430382
  - 36.84896788990825
  sm:
  - 3.2617021276596105
  - 8.600302233902823
  - 14.432620481927781

backbone: custom
block_layers: [1, 1, 1, 1]
resnet_config:
  block: BasicBlock
dropout: 0.4

melspectrogram_config:
  center: false
  hop_length: 1000
  mel_scale: htk
  n_fft: 1000
  n_mels: 32
  norm: slaney
  pad_mode: reflect
  power: 2
  win_length: null

mfcc_config:
  melkwargs:
    center: false
    hop_length: 1000
    mel_scale: htk
    n_fft: 1000
    n_mels: 32
    norm: slaney
    pad_mode: reflect
    power: 2
    win_length: null
  n_mfcc: 32

num_anchors: 3
sample_duration: 60
sample_rate: 44100
new_sample_rate: 16000
scale_input: true
taper_input: true
taper_window: hann

train_config:
  dataset_path: dataset/ivy
  annotation_file: annotation.json
  annotator: annotator_a
  batch_size: 32
  audio_extension: wav
  device: cuda
  epochs: 320

  loss_config:
    alpha: null
    anchor_t: 1.5
    batch_scale_loss: false
    box_w: 0.1
    class_w: 0.3
    conf_w: 0.6
    edge_t: 0.5
    gamma: null
    label_smoothing: 0.08
    multi_label: false

  optimizer_config:
    betas: [0.9, 0.999]
    eps: 1.0e-08
    lr: 0.001
    name: Adam
    weight_decay: 0.001

  lr_scheduler_config:
    T_0: 320
    T_mult: 1
    eta_min: 1.0e-06
    name: CosineAnnealingWarmRestarts

  ema_config:
    N: 2000
    momentum: 0.002
    num_updates: 0

  shuffle_samples: true
  use_ema: false
  use_lr_scheduler: true
  verbose: true
  metrics_path: metrics
  model_path: saved_model
