anchors:
  lg:
  - 43.19310559006211
  - 50.995572519083964
  - 59.81746359223294
  md:
  - 19.55103626943005
  - 27.203208722741433
  - 35.17562231759656
  sm:
  - 2.650371318822021
  - 7.444496919917864
  - 12.86779279279279

sample_rate: 22050
new_sample_rate: 16000
audio_extension: wav

melspectrogram_config:
  center: false
  hop_length: 1000
  mel_scale: htk
  n_fft: 1000
  n_mels: 32
  norm: slaney
  pad_mode: reflect
  power: 2
  win_length: null

mfcc_config:
  melkwargs:
    center: false
    hop_length: 1000
    mel_scale: htk
    n_fft: 1000
    n_mels: 32
    norm: slaney
    pad_mode: reflect
    power: 2
    win_length: null
  n_mfcc: 32

scale_input: true
num_anchors: 3
sample_duration: 60
taper_input: true
taper_window: hann
backbone: custom
block_layers: [1, 1, 1, 1]
dropout: 0.5

resnet_config:
  block: BasicBlock

train_config:
  annotation_file_path: dataset/annotations/MD_mapping.json
  annotator: annotator_a
  batch_size: 32
  device: cuda
  epochs: 320

  loss_config:
    label_smoothing: 0.01
    class_loss_w: 0.3
    obj_conf_loss_w: 1.0
    noobj_conf_loss_w: 1.0
    ciou_loss_w: 0.7
    sm_loss_w: 1.0
    md_loss_w: 1.0
    lg_loss_w: 1.0
    iou_gt_threshold: 0.5

  optimizer_config:
    lr: 0.001
    weight_decay: 5.0e-03
    betas: [0.9, 0.999]
    eps: 0.00000001
    name: Adam

  lr_scheduler_config:
    # gamma: 0.1
    # step_size: 160
    # last_epoch: -1
    # name: StepLR
    T_0: 320
    T_mult: 2
    eta_min: 1.0e-07
    name: CosineAnnealingWarmRestarts

  ema_config:
    momentum: 0.002
    num_updates: 0
    N: 2000

  metrics_path: metrics
  model_path: saved_model
  shuffle_samples: true
  use_lr_scheduler: true
  use_ema: false
  verbose: true